site_name: Workshop "Marketing Analytics" at JADS
site_url: https://github.io/hannesdatta/course-jads2020
#repo_url: https://github.com/hannesdatta/course-jads2020
repo_name: 'GitHub'
site_description: "Course syllabus for the Marketing Analytics sessions at JADS 's-Hertogenbosch in 2020."
site_author: Hannes Datta

nav:
- Home: index.md
- Syllabus and Preparation: 
    - Session 1: sessions/session1.md
    - Session 2: sessions/workflows.md
    - Session 3: sessions/session2.md
    - Session 4: sessions/scraping.md
    
#- Schedule: schedule.md
- About the instructors: about.md

theme:
  name: 'material'
  palette:
    #primary: 'Blue Grey' # default: indigo, other colors see https://squidfunk.github.io/mkdocs-material/getting-started/
    primary: 'indigo' # default: indigo, other colors see https://squidfunk.github.io/mkdocs-material/getting-started/
    accent: 'indigo'

markdown_extensions:
  - admonition
  - attr_list
  - footnotes

